/*

TREE:- A DATA STRUCTURE THAT CONSISTS OF NODES IN A PARENT/CHILD RELATIONSHIP

1. TREES ARE NON-LINEAR (LISTS ARE LINEAR)
2. SINGLY LINKED LIST IS A SPECIAL CASE OF TREE
3. NODES CAN ONLY POINT TO CHILD
4. TWO NODES CANT POINT TO EACH OTHER

Í
                -: TERMINOLOGY :-

ROOT :- THE TOP NODE IN A TREE
CHILD :- A NODE DIRECTLY CONNECTED TO ANOTHER NODE WHEN MOVING AWAY FROM THE ROOT
PARENT :- THE CONVERSE NOTION OF A CHILD
SIBLINGS :- A GROUP OF NODES WITH THE SAME PARENT
LEAF :- A NODE WITH NO CHILDREN
EDGE :- THE CONNECTION BETWEEN ONE NODE AND ANOTHER (ARROW)

                -: APPLICATIONS :-
1. HTML DOM
2. NETWORK ROUTING
3. ABSTRACT SYNTAX TREES
4. ARTIFICIAL INTELLIGENCE (MINIMAX TREE)
5. FOLDERS IN OPERATING SYSTEMS
6. COMPUTER FILE SYSTEMS

                -: KINDS OF TREES :-
1. TREES
2. BINARY TRESS
3. BINARY SEARCH TREES

*/

